version: "3.9"

services:
  sql-product:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-product
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Lackyline03!
    ports:
      - "14331:1433"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Lackyline03! -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      retries: 10
      start_period: 20s
      timeout: 3s

  sql-order:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-order
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Lackyline03!
    ports:
      - "14332:1433"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Lackyline03! -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      retries: 10
      start_period: 20s
      timeout: 3s

  sql-shipping:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-shipping
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Lackyline03!
    ports:
      - "14333:1433"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Lackyline03! -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      retries: 10
      start_period: 20s
      timeout: 3s

  sql-reviews:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-reviews
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Lackyline03!
    ports:
      - "14334:1433"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Lackyline03! -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      retries: 10
      start_period: 20s
      timeout: 3s

  sql-promotions:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-promotions
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Lackyline03!
    ports:
      - "14335:1433"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Lackyline03! -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      retries: 10
      start_period: 20s
      timeout: 3s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: eshop-net
